[2020-06-16 16:02:54,046][INFO] Start watching sub-server status ...
[2020-06-16 16:02:54,306][INFO] Connect to central server 192.168.1.37 success
[2020-06-16 16:02:54,306][INFO] Start sub-server http://192.168.1.37:8080
[2020-06-16 16:03:45,157][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,158][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,159][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,160][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,161][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,161][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,162][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,173][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,176][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,177][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,178][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,179][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,180][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,214][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,215][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,217][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,218][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,219][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,221][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,229][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,231][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,232][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,233][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,235][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,236][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,237][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,238][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,248][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,249][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,250][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,255][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,256][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,256][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,305][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,306][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,307][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,307][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,308][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,309][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,310][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,310][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,311][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,311][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,312][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,312][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,313][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,315][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,315][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,316][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,319][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,319][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,320][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,321][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,335][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,336][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,337][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,337][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,338][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,339][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,339][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,340][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,341][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,343][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,344][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,344][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,345][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,345][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,354][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,354][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,355][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,356][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,357][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,358][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,358][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,359][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,360][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,361][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,361][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,362][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,363][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,363][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,364][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,364][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,365][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,365][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,366][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,367][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,368][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,368][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,369][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,369][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,370][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,371][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,372][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,372][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,375][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,375][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,376][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,377][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,378][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,381][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,382][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,405][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,408][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,408][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,419][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,420][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,420][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,421][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,422][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,422][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,423][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,424][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,425][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,425][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,426][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,445][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,447][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,448][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,449][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,450][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,452][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,466][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,467][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,469][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,470][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,471][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,472][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,472][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,473][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,474][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,474][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,521][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,524][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,537][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,639][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,640][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:03:45,743][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:11,101][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:11,102][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:11,106][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:11,108][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:11,109][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:11,110][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:11,112][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:26,691][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:26,694][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:26,695][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:26,696][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:26,697][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:26,700][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:26,704][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:33,793][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:33,794][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:33,795][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:33,796][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:33,797][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:33,798][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:33,798][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:33,799][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:33,800][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:33,801][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:33,803][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:33,901][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:33,903][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:33,906][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:37,719][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:37,720][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:37,721][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:37,722][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:37,723][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:37,725][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:37,726][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:37,727][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:37,727][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:37,730][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:37,731][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:37,731][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:37,823][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:37,829][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:37,830][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:37,831][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:37,832][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:37,833][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:37,927][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:04:37,928][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:05:04,173][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:05:04,176][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:05:04,177][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:05:04,179][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:05:04,182][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:05:04,185][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

[2020-06-16 16:05:04,186][INFO] Data parse failed. 
Error: Traceback (most recent call last):
  File "/Users/bindo1111/Documents/trash/qauto_sub_server/core/http/monitoring.py", line 62, in monitoring
    post_data = json.loads(wsgi_data.decode(file_encoding))
ValueError: Expected object or value

